---
name: Test-flow
run-name: >-
  ${{ github.event.issue.number && format('test_flow | PR-{0}', github.event.issue.number)
  || 'Test Deployment' }}

permissions: read-all

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pipeline:
    runs-on: codebuild-test-codebuild-runner-terraform-infra-${{ github.run_id }}-${{ github.run_attempt }}
    name: test-workflow
    permissions: write-all


    ############## Test your branch by pushing to the test branch of this repo ############################
    steps:
      - name: Run Composite Module
        uses: TRI-IE/terraform-infra@test
